name: Ruby Gem

on:
  push:
    branches: ["main"]
    paths:
      - "lib/parquet/version.rb"
  pull_request:
    branches: ["main"]
    paths:
      - "lib/parquet/version.rb"
  workflow_dispatch:

jobs:
  build:
    name: Build + Publish
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build_type: normal
            platform: ruby
          - os: ubuntu-24.04
            arch: x86_64
            platform: linux
            build_type: native
            platform_name: x86_64-linux
            duckdb_url: "https://github.com/duckdb/duckdb/releases/download/v1.1.3/libduckdb-linux-amd64.zip"
          - os: ubuntu-24.04-arm
            arch: arm64
            platform: linux
            build_type: native
            platform_name: aarch64-linux
            duckdb_url: "https://github.com/duckdb/duckdb/releases/download/v1.1.3/libduckdb-linux-arm64.zip"
          - os: macos-latest
            arch: arm64
            platform: darwin
            build_type: native
            platform_name: arm64-darwin
            duckdb_url: "https://github.com/duckdb/duckdb/releases/download/v1.1.3/libduckdb-osx-universal.zip"
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    steps:
      - uses: actions/checkout@v4

      - name: Download and Install DuckDB
        if: matrix.build_type == 'native'
        run: |
          echo "Downloading DuckDB from ${{ matrix.duckdb_url }}"
          if [[ "${{ matrix.os }}" == ubuntu* ]]; then
            wget ${{ matrix.duckdb_url }} -O duckdb.zip
            unzip duckdb.zip
            sudo cp libduckdb.so /usr/local/lib/
            sudo cp duckdb.h duckdb.hpp /usr/local/include/
            sudo ldconfig
          else
            curl -L ${{ matrix.duckdb_url }} -o duckdb.zip
            unzip duckdb.zip
            sudo cp libduckdb.dylib /usr/local/lib/
            sudo cp duckdb.h duckdb.hpp /usr/local/include/
          fi

      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Build Normal Gem
        if: matrix.build_type == 'normal'
        run: |
          echo "Building normal gem without native extensions"
          gem build parquet.gemspec

      - name: Build Native Gem
        if: matrix.build_type == 'native'
        env:
          RUBY_PLATFORM: ${{ matrix.platform_name }}
        run: |
          echo "Building native gem for ${{ matrix.platform_name }}"
          gem build parquet.gemspec --platform=${{ matrix.platform_name }}

      - name: Publish Gem
        uses: rubygems/release-gem@v1

